### ISSUE TITLE
Gather sample set of 50 articles for post content 

### ISSUE THREAD

**Issue by daviswhitehead** [daviswhitehead/shayr#14]
sample post content should be loaded into the database for feed development

**Comment by jessewolf** [comment]
scoping this ticket down a little.

I will upload a csv of url's of a variety of content for Davis to test pulling info and adding to database

**Comment by jessewolf** [comment]
https://www.nytimes.com/2017/12/10/us/politics/richard-shelby-roy-moore.html
https://www.netflix.com/title/80057281?s=i&trkid=14170035
https://medium.com/astro-hq/camera-button-ba3d8c493cbd?source=userActivityShare-83495be9bdeb-1512935319
https://itunes.apple.com/us/podcast/this-american-life/id201671138?mt=2&i=1000395571218
http://allrecipes.com/recipe/12409/apple-crisp-ii/
https://www.rottentomatoes.com/m/coco_2017
https://www.amazon.com/Habits-Highly-Effective-People-Anniversary/dp/1511317299
https://www.youtube.com/watch?v=r0IQCLQDfKw
https://open.spotify.com/album/3pWJFrSX6apPzt4inM4zXt
https://www.reddit.com/r/worldnews/comments/7iv6s9/amazon_drivers_are_asked_to_deliver_up_to_200/
