### ISSUE TITLE
Design create/delete account and log in/out

### ISSUE THREAD

**Issue by daviswhitehead** [daviswhitehead/shayr#3]
Specs
- Decide on one mechanism (email, facebook, google)
  - Pull user's name and email
- Decide on how long to keep an account logged in
  - 2 weeks? one month?

**Comment by daviswhitehead** [comment]
facebook and google account creation

**Comment by jessewolf** [comment]
![image](https://user-images.githubusercontent.com/6842437/33807938-3d9feda8-ddac-11e7-9b4f-891cf2ee6aa9.png)
