### ISSUE TITLE
Design post objects

### ISSUE THREAD

**Issue by daviswhitehead** [daviswhitehead/shayr#4]
Design specs should follow decisions made on https://github.com/daviswhitehead/shayr/issues/1

**Comment by jessewolf** [comment]
MVP mocks:

![image](https://user-images.githubusercontent.com/6842437/33808477-23ae9f12-ddb5-11e7-95f8-1e0780e1cf30.png)

**Comment by jessewolf** [comment]
**post object will have:**
- image  (fallback to content default image if can't pull)
- title
- source (new york times, etc.)
- shared by name
