### ISSUE TITLE
Prototype or animate a sample mvp feed 

### ISSUE THREAD

**Issue by daviswhitehead** [daviswhitehead/shayr#8]
What is a feed?
- collection of posts

How does a user interact with the feed overall?
- scroll up and down
- refresh the feed

How does a user interact with the posts within the feed?
- swipe right and left
- tap

**Comment by jessewolf** [comment]
![image](https://user-images.githubusercontent.com/6842437/33808496-88436d18-ddb5-11e7-8e58-89be0256600a.png)

**Comment by jessewolf** [comment]
![image](https://user-images.githubusercontent.com/6842437/33808611-b918a5d2-ddb7-11e7-8e8a-be5cb0ff97a3.png)

**Comment by daviswhitehead** [comment]
done
