### ISSUE TITLE
prototype feedback design system

### ISSUE THREAD

**Issue by jessewolf** [daviswhitehead/shayr#83]
four MVP feedback mechanisms:
- SHAYRs
- QUEUE ADDs
- MARK AS DONEs
- LIKEs

Need icon and number treatment to be viewed on the following screens:
Post list view:
- FEED
- QUEUE
Post Detail:
- when tap on post in feed/queue

other notes:
- when it's something the user has made one of the feedback actions on then there is some visual indicator for that within the icon and potentially within the card
- in a more detailed view you can see which friends make up the feedback icon count

open questions:
- what does tapping on a shayr post card bring up (modal, post detail page, etc.)?

**Comment by daviswhitehead** [comment]
![image](https://user-images.githubusercontent.com/8632165/43228266-14f3ac9c-902f-11e8-8d00-9f03d9ed36cf.png)

**Comment by daviswhitehead** [comment]
Still outstanding... What does tapping on a row do? How do users find out the names of everyone else that has shayred or liked?

**Comment by daviswhitehead** [comment]
Still outstanding... What does tapping on a row do? How do users find out the names of everyone else that has shayred or liked?
